# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/Audio_Capture.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/Debounced_Signal.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/Draw_Pixel.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/Manual_Display.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/Oled_Display.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/Precise_Clock.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/Shifting_Oled.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/assign_cm.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/btn_status.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/calibrations.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/callibrate2.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/callibrate3.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/callibrate4.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/clk20k.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/yz/EE2026_Project.srcs/sources_1/new/clk_one_sec.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/convert_to_seg.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/convert_to_seg_decimal.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/count5_1.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/count5_2.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/count5_3.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/count5_4.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/display_plexer.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/display_val.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/yz/EE2026_Project.srcs/sources_1/new/draw_game_screen.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/draw_menu.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/yz/EE2026_Project.srcs/sources_1/new/game_best_logic.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/led_tap_score.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/my_dff.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/precise_clk.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/return.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/yz/EE2026_Project.srcs/sources_1/new/score_generator.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/seg_assign.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/segments_display.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/show_ratings.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/show_speed.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/simulate_led.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/slow_clock.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/Project/yz/EE2026_Project.srcs/sources_1/new/sonar_display.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/tuning1.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/imports/EE2026/volume_display_two.v}
  {C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/sources_1/new/top_student.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/constrs_1/new/constraint.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Falicia Ong/Documents/EE2026_Project/EE2026_Project.srcs/constrs_1/new/constraint.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_student -part xc7a35ticpg236-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_student_utilization_synth.rpt -pb top_student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
